// InstaLearning - Default Word List (German ↔ Dutch)

export const DEFAULT_WORDS = [
  { id: "w1", german: "Hund", dutch: "Hond", emoji: "🐕", example: "Der Hund spielt im Garten" },
  { id: "w2", german: "Katze", dutch: "Kat", emoji: "🐱", example: "Die Katze schläft auf dem Sofa" },
  { id: "w3", german: "Haus", dutch: "Huis", emoji: "🏠", example: "Das Haus ist sehr groß" },
  { id: "w4", german: "Wasser", dutch: "Water", emoji: "💧", example: "Ich trinke viel Wasser" },
  { id: "w5", german: "Brot", dutch: "Brood", emoji: "🍞", example: "Das Brot ist frisch" },
  { id: "w6", german: "Milch", dutch: "Melk", emoji: "🥛", example: "Die Milch ist kalt" },
  { id: "w7", german: "Apfel", dutch: "Appel", emoji: "🍎", example: "Der Apfel ist rot" },
  { id: "w8", german: "Buch", dutch: "Boek", emoji: "📖", example: "Ich lese ein Book" },
  { id: "w9", german: "Tisch", dutch: "Tafel", emoji: "🪑", example: "Der Tisch ist aus Holz" },
  { id: "w10", german: "Stuhl", dutch: "Stoel", emoji: "🪑", example: "Der Stuhl ist bequem" },
  { id: "w11", german: "Fenster", dutch: "Raam", emoji: "🪟", example: "Das Fenster ist offen" },
  { id: "w12", german: "Tür", dutch: "Deur", emoji: "🚪", example: "Die Tür ist geschlossen" },
  { id: "w13", german: "Auto", dutch: "Auto", emoji: "🚗", example: "Das Auto ist schnell" },
  { id: "w14", german: "Fahrrad", dutch: "Fiets", emoji: "🚲", example: "Ich fahre mit dem Fahrrad" },
  { id: "w15", german: "Straße", dutch: "Straat", emoji: "🛣️", example: "Die Straße ist lang" },
  { id: "w16", german: "Stadt", dutch: "Stad", emoji: "🏙️", example: "Die Stadt ist groß" },
  { id: "w17", german: "Land", dutch: "Land", emoji: "🌍", example: "Das Land ist schön" },
  { id: "w18", german: "Baum", dutch: "Boom", emoji: "🌳", example: "Der Baum ist hoch" },
  { id: "w19", german: "Blume", dutch: "Bloem", emoji: "🌸", example: "Die Blume ist schön" },
  { id: "w20", german: "Sonne", dutch: "Zon", emoji: "☀️", example: "Die Sonne scheint" },
  { id: "w21", german: "Mond", dutch: "Maan", emoji: "🌙", example: "Der Mond ist voll" },
  { id: "w22", german: "Stern", dutch: "Ster", emoji: "⭐", example: "Der Stern leuchtet" },
  { id: "w23", german: "Himmel", dutch: "Hemel", emoji: "🌤️", example: "Der Himmel ist blau" },
  { id: "w24", german: "Wolke", dutch: "Wolk", emoji: "☁️", example: "Die Wolke ist weiß" },
  { id: "w25", german: "Regen", dutch: "Regen", emoji: "🌧️", example: "Der Regen fällt" },
  { id: "w26", german: "Schnee", dutch: "Sneeuw", emoji: "❄️", example: "Der Schnee ist weiß" },
  { id: "w27", german: "Wind", dutch: "Wind", emoji: "💨", example: "Der Wind ist stark" },
  { id: "w28", german: "Feuer", dutch: "Vuur", emoji: "🔥", example: "Das Feuer ist heiß" },
  { id: "w29", german: "Erde", dutch: "Aarde", emoji: "🌍", example: "Die Erde ist rund" },
  { id: "w30", german: "Meer", dutch: "Zee", emoji: "🌊", example: "Das Meer ist tief" },
  { id: "w31", german: "Fluss", dutch: "Rivier", emoji: "🏞️", example: "Der Fluss fließt schnell" },
  { id: "w32", german: "Berg", dutch: "Berg", emoji: "⛰️", example: "Der Berg ist hoch" },
  { id: "w33", german: "Wald", dutch: "Bos", emoji: "🌲", example: "Der Wald ist dunkel" },
  { id: "w34", german: "Garten", dutch: "Tuin", emoji: "🏡", example: "Der Garten ist grün" },
  { id: "w35", german: "Küche", dutch: "Keuken", emoji: "🍳", example: "Die Küche ist sauber" },
  { id: "w36", german: "Schlafzimmer", dutch: "Slaapkamer", emoji: "🛏️", example: "Das Schlafzimmer ist ruhig" },
  { id: "w37", german: "Badezimmer", dutch: "Badkamer", emoji: "🛁", example: "Das Badezimmer ist klein" },
  { id: "w38", german: "Arbeit", dutch: "Werk", emoji: "💼", example: "Die Arbeit ist wichtig" },
  { id: "w39", german: "Schule", dutch: "School", emoji: "🏫", example: "Die Schule beginnt um acht" },
  { id: "w40", german: "Freund", dutch: "Vriend", emoji: "👫", example: "Mein Freund ist nett" },
  { id: "w41", german: "Familie", dutch: "Familie", emoji: "👨‍👩‍👧‍👦", example: "Die Familie isst zusammen" },
  { id: "w42", german: "Mutter", dutch: "Moeder", emoji: "👩", example: "Meine Mutter kocht gut" },
  { id: "w43", german: "Vater", dutch: "Vader", emoji: "👨", example: "Mein Vater arbeitet viel" },
  { id: "w44", german: "Kind", dutch: "Kind", emoji: "👶", example: "Das Kind speelt draußen" },
  { id: "w45", german: "Bruder", dutch: "Broer", emoji: "👦", example: "Mein Bruder ist älter" },
  { id: "w46", german: "Schwester", dutch: "Zus", emoji: "👧", example: "Meine Schwester singt gern" },
  { id: "w47", german: "Liebe", dutch: "Liefde", emoji: "❤️", example: "Die Liebe ist stark" },
  { id: "w48", german: "Zeit", dutch: "Tijd", emoji: "⏰", example: "Die Zeit vergeht schnell" },
  { id: "w49", german: "Tag", dutch: "Dag", emoji: "🌞", example: "Der Tag ist lang" },
  { id: "w50", german: "Nacht", dutch: "Nacht", emoji: "🌙", example: "Die Nacht ist dunkel" },
  { id: "w51", german: "Morgen", dutch: "Ochtend", emoji: "🌅", example: "Der Morgen ist frisch" },
  { id: "w52", german: "Abend", dutch: "Avond", emoji: "🌆", example: "Der Abend ist schön" },
  { id: "w53", german: "Jahr", dutch: "Jaar", emoji: "📅", example: "Das Jahr hat zwölf Monate" },
  { id: "w54", german: "Monat", dutch: "Maand", emoji: "🗓️", example: "Der Monat ist fast vorbei" },
  { id: "w55", german: "Woche", dutch: "Week", emoji: "📆", example: "Die Woche hat sieben Tage" },
  { id: "w56", german: "Heute", dutch: "Vandaag", emoji: "📍", example: "Heute ist ein guter Tag" },
  { id: "w57", german: "Gestern", dutch: "Gisteren", emoji: "⏪", example: "Gestern war es kalt" },
  { id: "w58", german: "Essen", dutch: "Eten", emoji: "🍽️", example: "Das Essen schmeckt gut" },
  { id: "w59", german: "Trinken", dutch: "Drinken", emoji: "🥤", example: "Ich möchte etwas trinken" },
  { id: "w60", german: "Schlafen", dutch: "Slapen", emoji: "😴", example: "Ich muss schlafen gehen" },
  { id: "w61", german: "Gehen", dutch: "Gaan", emoji: "🚶", example: "Wir gehen nach Hause" },
  { id: "w62", german: "Kommen", dutch: "Komen", emoji: "🏃", example: "Sie kommen morgen" },
  { id: "w63", german: "Sehen", dutch: "Zien", emoji: "👀", example: "Ich kann dich sehen" },
  { id: "w64", german: "Hören", dutch: "Horen", emoji: "👂", example: "Ich höre Musik" },
  { id: "w65", german: "Sprechen", dutch: "Spreken", emoji: "🗣️", example: "Er spricht Deutsch" },
  { id: "w66", german: "Lesen", dutch: "Lezen", emoji: "📚", example: "Sie liest ein Buch" },
  { id: "w67", german: "Schreiben", dutch: "Schrijven", emoji: "✍️", example: "Ich schreibe einen Brief" },
  { id: "w68", german: "Lernen", dutch: "Leren", emoji: "🎓", example: "Wir lernen Niederländisch" },
  { id: "w69", german: "Spielen", dutch: "Spelen", emoji: "🎮", example: "Die Kinder spielen" },
  { id: "w70", german: "Lachen", dutch: "Lachen", emoji: "😄", example: "Sie lacht viel" },
  { id: "w71", german: "Weinen", dutch: "Huilen", emoji: "😢", example: "Das Baby weint" },
  { id: "w72", german: "Groß", dutch: "Groot", emoji: "📏", example: "Der Elefant ist groß" },
  { id: "w73", german: "Klein", dutch: "Klein", emoji: "🐜", example: "Die Ameise ist klein" },
  { id: "w74", german: "Gut", dutch: "Goed", emoji: "👍", example: "Das ist sehr gut" },
  { id: "w75", german: "Schlecht", dutch: "Slecht", emoji: "👎", example: "Das Wetter ist schlecht" },
  { id: "w76", german: "Schön", dutch: "Mooi", emoji: "✨", example: "Die Blume ist schön" },
  { id: "w77", german: "Hässlich", dutch: "Lelijk", emoji: "👹", example: "Das Monster ist hässlich" },
  { id: "w78", german: "Schnell", dutch: "Snel", emoji: "⚡", example: "Der Zug ist schnell" },
  { id: "w79", german: "Langsam", dutch: "Langzaam", emoji: "🐢", example: "Die Schildkröte ist langsam" },
  { id: "w80", german: "Neu", dutch: "Nieuw", emoji: "🆕", example: "Das Auto ist neu" },
  { id: "w81", german: "Alt", dutch: "Oud", emoji: "🏛️", example: "Das Gebäude ist alt" },
  { id: "w82", german: "Jung", dutch: "Jong", emoji: "👶", example: "Das Kind ist jung" },
  { id: "w83", german: "Warm", dutch: "Warm", emoji: "🌡️", example: "Der Sommer ist warm" },
  { id: "w84", german: "Kalt", dutch: "Koud", emoji: "🥶", example: "Der Winter ist kalt" },
  { id: "w85", german: "Eins", dutch: "Een", emoji: "1️⃣", example: "Ich habe eins" },
  { id: "w86", german: "Zwei", dutch: "Twee", emoji: "2️⃣", example: "Zwei plus zwei ist vier" },
  { id: "w87", german: "Drei", dutch: "Drie", emoji: "3️⃣", example: "Ich habe drei Äpfel" },
  { id: "w88", german: "Vier", dutch: "Vier", emoji: "4️⃣", example: "Das Zimmer hat vier Ecken" },
  { id: "w89", german: "Fünf", dutch: "Vijf", emoji: "5️⃣", example: "Ich habe fünf Finger" },
  { id: "w90", german: "Rot", dutch: "Rood", emoji: "🔴", example: "Die Tomate ist rot" },
  { id: "w91", german: "Blau", dutch: "Blauw", emoji: "🔵", example: "Der Himmel ist blau" },
  { id: "w92", german: "Grün", dutch: "Groen", emoji: "🟢", example: "Das Gras ist grün" },
  { id: "w93", german: "Gelb", dutch: "Geel", emoji: "🟡", example: "Die Sonne ist gelb" },
  { id: "w94", german: "Schwarz", dutch: "Zwart", emoji: "⚫", example: "Die Nacht ist schwarz" },
  { id: "w95", german: "Weiß", dutch: "Wit", emoji: "⚪", example: "Der Schnee ist weiß" },
  { id: "w96", german: "Vogel", dutch: "Vogel", emoji: "🐦", example: "Der Vogel singt" },
  { id: "w97", german: "Fisch", dutch: "Vis", emoji: "🐟", example: "Der Fisch schwimmt" },
  { id: "w98", german: "Pferd", dutch: "Paard", emoji: "🐴", example: "Das Pferd läuft schnell" },
  { id: "w99", german: "Kuh", dutch: "Koe", emoji: "🐄", example: "Die Kuh gibt Milch" },
  { id: "w100", german: "Schwein", dutch: "Varken", emoji: "🐷", example: "Das Schwein ist rosa" }
];
